<?php
/** 
 * @file
 * Modifies where taxonomy links point to 
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function taxonomy_links_help($path, $arg) {
  switch ($path) {
    case "admin/help#taxonomy_links":
      return '<p>' . t("Modifies where taxonomy links point to") . '</p>';
      break;
  }
} 


function taxonomy_links_entity_info_alter(&$entity_info) {
  $entity_info['taxonomy_term']['uri callback'] = 'taxonomy_links_taxonomy_term_uri';
}




function taxonomy_links_taxonomy_term_uri($term) {
 return array('path' => 'browse-all?field_'. $term->vocabulary_machine_name . '_tid[]=' . $term->tid . '&keys=');
}



