# Host filesystem
htdocs: htdocs    # document root expected by apache
htsdocs: htsdocs  # ibid.
file_owner: aten
file_group: www-data
site_directory:             # typically the same as the domain name
sites_directory: /var/www
