ds_search.settings:
  type: mapping
  label: 'Display Suite search settings'
  mapping:
    view_mode:
      label: 'View mode'

# Plugin \Drupal\node\Plugin\Search\NodeSearch
search.plugin.ds_node_search:
  type: mapping
  label: 'Content search'
  mapping:
    rankings:
      type: sequence
      label: 'Content ranking'
      sequence:
        - type: integer
          label: 'Influence'
    view_mode:
      label: 'View Mode'
    advanced_search:
      type: boolean
      label: 'Enable advanced search'
    limit:
      type: integer
      label: 'Number of nodes per page'
    search_variables:
      label: 'Extra information inserted into the search results'
    show_title:
      type: boolean
      label: 'Show title on search result page'
    highlight:
      type: boolean
      label: 'Highlight words in search results'
    highlight_selector:
      label: 'The selector of the region wherein a keyword should be highlighted'

# Plugin \Drupal\user\Plugin\Search\UserSearch
search.plugin.ds_user_search:
  type: mapping
  label: 'User search'
  mapping:
    rankings:
      type: sequence
      label: 'Content ranking'
      sequence:
        - type: integer
          label: 'Influence'
    view_mode:
      label: 'View Mode'
    limit:
      type: integer
      label: 'Number of nodes per page'
    search_variables:
      label: 'Extra information inserted into the search results'
    show_title:
      type: boolean
      label: 'Show title on search result page'
    highlight:
      type: boolean
      label: 'Highlight words in search results'
    highlight_selector:
      label: 'The selector of the region wherein a keyword should be highlighted'
