<!-- Widget Page Template -->
<head>
<style> 
	body {
	//background-color: #e4f3ea;
	font-size: 1.7em;
}
</style>
<base target="_parent" />
</head>


<!-- Array of Beginner Tips -->
<?php  
$textArray = array('<a href="http://csteachingtips.org/tip/have-students-make-themselves-cheat-sheets-so-they-are-able-quickly-look-syntax-which-keeps-them">Have students make themselves cheat sheets so they are able to quickly look up syntax, which keeps them from spending too much time looking up these facts.</a>',
'<a href="http://csteachingtips.org/tip/ask-students-consider-which-objects-room-are-computers-further-their-understanding-what">Ask students to consider which objects in the room are computers to further their understanding of what computing is.</a>',
'<a href="http://csteachingtips.org/tip/use-pbj-sandwich-activity-introduce-important-components-algorithms">Use the "PB&J" sandwich activity to introduce important components of algorithms.</a>',
'<a href="http://csteachingtips.org/tip/create-program-where-local-high-school-students-come-your-elementary-school-teach-younger">Create a program where local high school students come to your elementary school to teach younger students computer science in order to give your students relatable role models.</a>',
'<a href="http://csteachingtips.org/tip/have-students-pair-program-increase-their-interactions-one-another-which-can-promote-retention">Have students pair program to increase their interactions with one another, which can promote retention of female students.</a>',
'<a href="http://csteachingtips.org/tip/have-students-create-websites-about-topic-they-find-meaningful-motivate-learning-html-and-css">Have students create websites about a topic they find meaningful to motivate learning HTML and CSS.</a>',
'<a href="http://csteachingtips.org/tip/use-random-method-selecting-students-answer-questions-order-give-all-students-equal-opportunity">Use a random method for selecting students to answer questions in order to give all students an equal opportunity to participate.</a>',
'<a href="http://csteachingtips.org/tip/don%E2%80%99t-express-shock-or-%E2%80%9Ccompliment%E2%80%9D-students-breaking-stereotypes-associated-their-race-or">Don’t express shock or “compliment” students for breaking stereotypes associated with their race or gender; these statements are microaggressions, they discriminate against these students, often unintentionally.</a>',
'<a href="http://csteachingtips.org/tip/identify-jobs-within-your-school-and-school-district-are-staffed-computer-scientists-and-share">Identify the jobs within your school and school district that are staffed by computer scientists and share this with students so they see that computers scientists work everywhere.</a>',
'<a href="http://csteachingtips.org/tip/encourage-students-work-side-projects-make-sure-they-are-getting-enough-programming-practice-and">Encourage students to work on side projects to make sure they are getting enough programming practice and to make them more marketable.</a>',
'<a href="http://csteachingtips.org/tip/assure-students-you-don%E2%80%99t-need-very-much-math-learn-computer-science-reduce-their-stress">Assure students that you don’t need very much math to learn computer science to reduce their stress.</a>',
'<a href="http://csteachingtips.org/tip/include-statements-accommodating-students-disabilities-your-syllabus-and-your-website-make-it">Include statements for accommodating students with disabilities in your syllabus and on your website to make it easily available.</a>',
'<a href="http://csteachingtips.org/tip/when-students-are-working-open-ended-projects-resist-urge-intervene">When students are working on open-ended projects, resist the urge to intervene!</a>',
'<a href="http://csteachingtips.org/tip/assign-procedural-roles-students-working-groups-create-most-equitable-environment">Assign procedural roles to students working in groups to create the most equitable environment.</a>',
'<a href="http://csteachingtips.org/tip/use-physical-activity-class-combat-stereotypes-about-what-computer-science-and-computer">Use physical activity in class to combat stereotypes about what computer science and computer scientists are like.</a>',
'<a href="http://csteachingtips.org/tip/allocate-computer-time-evenly-among-students-especially-elementary-school-so-all-students-get">Allocate computer time evenly among students, especially in elementary school, so all students get a chance to play.</a>',
'<a href="http://csteachingtips.org/tip/write-made-examples-avoid-unknowingly-introducing-culturally-biased-problems">Write made-up examples to avoid unknowingly introducing culturally-biased problems.</a>',
'<a href="http://csteachingtips.org/tip/show-students-diverse-set-people-who-hold-cs-careers-make-sure-it%E2%80%99s-clear-there-no-one-person-or">Show students the diverse set of people who hold CS careers. Make sure it’s clear that there is no one person, or one personality that exemplifies the field.</a>',
'<a href="http://csteachingtips.org/tip/ensure-equitable-access-your-classroom-don%E2%80%99t-allow-language-reinforcing-idea-computer-science-">To ensure equitable access in your classroom, don’t allow language reinforcing the idea that computer science is “guy stuff” in the classroom, even passively.</a>',
'<a href="http://csteachingtips.org/tip/emphasize-having-more-experience-does-not-make-some-students-smarter-others">Emphasize that having more experience does not make some students smarter than others.</a>',
'<a href="http://csteachingtips.org/tip/use-resources-students-are-likely-access-independently-maximize-their-use">Use resources that students are likely to access independently to maximize their use.</a>',
'<a href="http://csteachingtips.org/tip/discuss-students%E2%80%99-goals-and-expectations-course-early-stimulate-interest">Discuss students’ goals and expectations for the course early on to stimulate interest.</a>',
'<a href="http://csteachingtips.org/tip/emphasize-computer-science-teaches-way-think-can-be-used-careers-tech-industry-and-beyond">Emphasize that computer science teaches a way to think that can be used in careers in the tech industry and beyond.</a>',
'<a href="http://csteachingtips.org/tip/have-students-greet-you-professionally-shaking-their-hand-they-come-classroom-first-day">Have students greet you professionally by shaking their hand as they come in the classroom on the first day!</a>',
'<a href="http://csteachingtips.org/tip/praise-students-receiving-feedback-well-encourage-them-be-open-and-receptive-when-they-get">Praise students for receiving feedback well to encourage them to be open and receptive when they get information that will help them improve their learning.</a>',
'<a href="http://csteachingtips.org/tip/reward-students-when-they-catch-mistake-or-ask-question-you-can%E2%80%99t-answer-encourage-critical">Reward students when they catch a mistake or ask a question you can’t answer to encourage critical thinking and engagement.</a>',
'<a href="http://csteachingtips.org/tip/remind-students-you%E2%80%99re-there-help-them-especially-when-students-apologize-asking-question">Remind students that you’re there to help them, especially when students apologize for asking a question.</a>',
'<a href="http://csteachingtips.org/tip/keep-running-list-bugs-you-encounter-share-students-so-they-can-see-you-run-bugs-too">Keep a running list of bugs you encounter to share with students so that they can see you run into bugs too.</a>',
'<a href="http://csteachingtips.org/tip/put-more-time-explaining-content-you-think-necessary-because-students-may-not-retain-all">Put more time into explaining content than you think is necessary because students may not retain all the material the first time you explain it.</a>',
'<a href="http://csteachingtips.org/tip/encourage-students-ask-questions-about-homework-assignments-class-because-other-students-may-be">Encourage students to ask questions about homework assignments in class, because other students may be struggling with the same question.</a>',
'<a href="http://csteachingtips.org/tip/have-students-write-pseudocode-pre-lab-exercise-so-they-are-prepared-write-code-when-lab-begins">Have students write pseudocode as a pre-lab exercise so they are prepared to write code when lab begins.</a>',
'<a href="http://csteachingtips.org/tip/teach-students-use-system-inquiry-testing-and-refining-debug-their-code-develop-better-coding">Teach students to use a system of inquiry, testing, and refining to debug their code, develop better coding habits, and deal with their frustration.</a>',
'<a href="http://csteachingtips.org/tip/encourage-students-who-have-worked-ahead-codeorg-curriculum-explore-playlab-so-they-can-use">Encourage students who have worked ahead in the Code.org curriculum to explore PlayLab so they can use their time constructively by continuing to code.</a>',
'<a href="http://csteachingtips.org/tip/integrate-hour-code-your-course-curriculum-having-students-turn-something-their-completed-hour">Integrate Hour of Code into your course curriculum by having students turn something in for their completed Hour of Code to hold them accountable for their work and prevent this from feeling like a one-off event.</a>',
'<a href="http://csteachingtips.org/tip/let-students-know-programming-educational-languages-scratch-or-python-valuable-even-though-these">Let students know that programming in educational languages like Scratch is valuable even though these languages aren’t commonly used in industry.</a>',
'<a href="http://csteachingtips.org/tip/assess-how-much-your-students-know-about-material-beginning-and-end-each-class-help-them-track">Assess how much your students know about the material at the beginning and the end of each class to help them track their progress in order to motivate hard work and validate their efforts.</a>',
'<a href="http://csteachingtips.org/tip/create-anticipation-guide-elicit-prior-knowledge-identify-misconceptions-and-prepare-students">Create an anticipation guide to elicit prior knowledge, identify misconceptions, and prepare students for a lesson.</a>',
'<a href="http://csteachingtips.org/tip/line-students-according-their-familiarity-concept-then-pair-nearby-students-so-students-can-work">Line students up according to their familiarity with a concept, then pair nearby students so that students can work together in pairs more comfortably because of similar content competency.</a>',
'<a href="http://csteachingtips.org/tip/help-students-get-their-development-environment-and-running-during-first-class-avoid">Help students get their development environment up and running during the first class to avoid technological problems as the class progresses.</a>',
'<a href="http://csteachingtips.org/tip/show-students-final-version-project-multiple-steps-motivate-them-and-give-them-perspective">Show students the final version of a project with multiple steps to motivate them and give them perspective.</a>',
'<a href="http://csteachingtips.org/tip/remain-calm-when-students-get-stuck-question-avoid-alarming-students">Remain calm when students get stuck on a question to avoid alarming students.</a>',
'<a href="http://csteachingtips.org/tip/tell-stories-about-your-experiences-learning-help-students-understand-they%E2%80%99re-not-alone-their">Tell stories about your experiences learning to help students understand that they’re not alone in their struggles and successes.</a>',
'<a href="http://csteachingtips.org/tip/have-students-do-most-frustrating-tasks-class-so-you-can-support-them-when-they-get-stuck-and">Have students do the most frustrating tasks in class, so that you can support them when they get stuck and prevent them from giving up or become overwhelmingly flustered.</a>',
'<a href="http://csteachingtips.org/tip/emphasize-students-visual-programming-languages-scratch-are-bona-fide-computer-programming">Emphasize to students that visual programming languages like Scratch are bona fide computer programming languages.</a>',
'<a href="http://csteachingtips.org/tip/when-learning-playful-context-students-are-less-likely-be-frustrated-difficulty-or-failure">When learning in a playful context, students are less likely to be frustrated by difficulty or failure.</a>',
'<a href="http://csteachingtips.org/tip/when-talking-through-your-thought-process-students-check-them-ensure-they%E2%80%99re-following-along">When talking through your thought process with students, check in with them to ensure they’re following along.</a>',
'<a href="http://csteachingtips.org/tip/introduce-new-concept-having-students-modify-existing-well-defined-programs-writing-programs">Introduce a new concept by having students modify existing, well-defined programs before writing programs from scratch.</a>',
'<a href="http://csteachingtips.org/tip/emphasize-it%E2%80%99s-never-too-late-get-help">Emphasize that it’s never too late to get help.</a>',
'<a href="http://csteachingtips.org/tip/if-students-are-worried-about-starting-assignment-give-them-explicit-first-step">If students are worried about starting an assignment, give them an explicit first step.</a>',
'<a href="http://csteachingtips.org/tip/tell-students-%E2%80%9Cit%E2%80%99s-not-about-understanding-immediately-not-giving-and-trying-until-you-do%E2%80%9D">Tell students: “It’s not about understanding immediately, but not giving up and trying until you do.”</a>',
'<a href="http://csteachingtips.org/tip/help-students-feel-comfortable-finding-bugs-showing-them-your-own-and-asking-debugging">Help students feel comfortable finding bugs by showing them your own and asking for debugging suggestions.</a>',
'<a href="http://csteachingtips.org/tip/when-student-interjects-discussion-better-solution-remind-class-there-are-multiple-ways-solve">When a student interjects a discussion with a "better" solution, remind the class that there are multiple ways to solve a problem.</a>',
'<a href="http://csteachingtips.org/tip/prevent-expert-students-dominating-during-class-not-validating-interruptive-show-offy-behavior">Prevent expert students from dominating during class by not validating interruptive, show-offy behavior.</a>',
'<a href="http://csteachingtips.org/tip/write-code-class-so-your-students-can-see-process-you%E2%80%99re-going-through">Write code in class so that your students can see the process you’re going through.</a>',
'<a href="http://csteachingtips.org/tip/moderate-group-discussion-teams-have-trouble-working-together-resolve-disagreements-and">Moderate a group discussion with teams that have trouble working together to resolve disagreements and encourage collaboration in a constructive way.</a>',
'<a href="http://csteachingtips.org/tip/incorporate-student-presentations-your-class-form-assessment-so-students-develop-their-public">Incorporate student presentations into your class as a form of assessment so that students develop their public speaking skills.</a>',
'<a href="http://csteachingtips.org/tip/ask-students-what-they-found-confusing-end-each-week-identify-problems-so-you-can-tailor-future">Ask students what they found confusing at the end of each week to identify problems so you can tailor future instruction to students needs.</a>',
'<a href="http://csteachingtips.org/tip/trace-through-code-class-so-students-feel-more-comfortable-doing-it-their-own">Trace through code in class so students feel more comfortable doing it on their own.</a>',
'<a href="http://csteachingtips.org/tip/encourage-students-make-variables-visible-scratch-help-them-debug-their-code">Encourage students to make variables visible in Scratch to help them debug their code.</a>',
'<a href="http://csteachingtips.org/tip/encourage-students-make-scratch-sprites-smaller-when-making-games-order-ease-game-play-and-make">Encourage students to make Scratch sprites smaller when making games in order to ease game play and make it more fun.</a>',
'<a href="http://csteachingtips.org/tip/encourage-students-break-their-scratch-scripts-smaller-chunks-help-them-test-and-debug-their">Encourage students to break up their Scratch scripts into smaller chunks to help them test and debug their code.</a>',
'<a href="http://csteachingtips.org/tip/misconception-students-get-confused-about-whether-set-or-change-variables-scratch">Misconception: Students get confused about whether to set or change variables in Scratch.</a>',
'<a href="http://csteachingtips.org/tip/have-students-create-reset-script-and-it-store-their-scratch-backpack-so-they-can-use-future-set">Have students create a reset script and it store in their Scratch backpack so they can use in the future to set the Stage back to a uniform starting point.</a>',
'<a href="http://csteachingtips.org/tip/have-students-analyze-effects-changing-pieces-loop-improve-their-understanding-loop-structure">Have students analyze the effects of changing pieces of a loop to improve their understanding of loop structure.</a>',
'<a href="http://csteachingtips.org/tip/misconception-students-think-%E2%80%9Crepeat-1%E2%80%9D-block-scratch-will-execute-relevant-script-twice-where">Misconception: Students think that a “repeat 1” block in Scratch will execute the relevant script twice, where the script executes once and then repeats once.</a>',
'<a href="http://csteachingtips.org/tip/teach-students-total-turn-theorem-help-them-reason-about-drawing-regular-closed-polygons-scratch">Teach students the Total Turn Theorem to help them reason about drawing regular, closed polygons in Scratch.</a>',
'<a href="http://csteachingtips.org/tip/misconception-students-think-%E2%80%9Cturn%E2%80%9D-blocks-scratch-imply-change-position-within-coordinate-plane">Misconception: Students think that “turn” blocks in Scratch imply a change in position within the coordinate plane.</a>',
'<a href="http://csteachingtips.org/tip/start-teaching-scratch-blocks-run-set-amount-time-avoid-common-misconception-blocks-are-executed">Start teaching Scratch with blocks that run for a set amount of time to avoid the common misconception that blocks are executed simultaneously.</a>',
'<a href="http://csteachingtips.org/tip/tell-young-students-computer-programming-simply-writing-rules-computer-follow-similar-bossing">Tell young students that computer programming is simply writing rules for a computer to follow, similar to bossing around a younger sibling, to help them connect programming to everyday life.</a>',
'<a href="http://csteachingtips.org/tip/show-students-examples-unreachable-code-help-them-reason-about-how-conditionals-are-executed">Show students examples of unreachable code to help them reason about how conditionals are executed.</a>',
'<a href="http://csteachingtips.org/tip/misconception-students-forget-without-instructions-other-users-won%E2%80%99t-know-how-correctly-run">Misconception: Students forget that without instructions, other users won’t know how to correctly run their code in Scratch.</a>',
'<a href="http://csteachingtips.org/tip/explicitly-show-students-how-login-scratch-because-not-all-students-have-same-level-computer">Explicitly show students how to login to Scratch because not all students have the same level of computer literacy.</a>',
'<a href="http://csteachingtips.org/tip/misconception-students-often-have-1-errors-when-working-loops-which-can-result-mixing-and-well">Misconception: Students often have off by 1 errors when working with loops, which can result from mixing up > and >= as well as forgetting that arrays start at index 0.</a>',
'<a href="http://csteachingtips.org/tip/misconception-students-think-both-if-and-else-cases-conditional-are-executed-every-single-time">Misconception: Students think that both the IF and the ELSE cases of a conditional are executed every single time a conditional runs.</a>',
'<a href="http://csteachingtips.org/tip/have-some-students-act-robots-while-their-peers-give-them-instructions-teach-students-how">Have some students act as robots while their peers give them instructions to teach students how to interact with and think like machines.</a>',
'<a href="http://csteachingtips.org/tip/use-droplet-blocks-based-text-editor-help-bridge-students%E2%80%99-learning-gap-between-blocks-and-text">Use Droplet, a blocks-based text editor, to help bridge students’ learning gap between blocks and text.</a>',
'<a href="http://csteachingtips.org/tip/emphasize-importance-developing-consistent-naming-schema-when-programming-part-good-style">Emphasize the importance of developing a consistent naming schema when programming as a part of good style.</a>',
	);

?>

<!-- Randomizing and Printing of Beginner Tip -->

<?php $randIndex = array_rand($textArray, 1);?>

<?php print $textArray[$randIndex]; ?>
